export { default as HomePage } from './home/HomePage.vue'
export { default as AboutPage } from './about/AboutPage.vue'
export { default as RoomPage } from './room/RoomPage.vue'
export { default as AuthPage } from './auth/AuthPage.vue'
export { default as ProfilePage } from './profile/ProfilePage.vue'